### ISSUE TITLE
wrong url for getting map info

### ISSUE THREAD

**Issue by hundredrabh** [mykle1/MMM-SunRiseSet#1]
Hi,
The url for getting map does not return an image.
"img.src = "http://api.usno.navy.mil/imagery/earth.png?date=today&seed=" + getTimeStamp; " 
needs to change to ...

"

+       var dd = today.date();^M
+       var mm = today.month()+1; //January is 0!^M
+       var yyyy = today.year();^M
+       var GMTtime = today.format("h:mm a");^M
+       if(dd<10){^M
+           dd='0'+dd;^M
+       } ^M
+       if(mm<10){^M
+           mm='0'+mm;^M
+       } ^M
+       var today = mm+'/'+dd+'/'+yyyy;^M
+               img.src = "http://api.usno.navy.mil/imagery/earth.png?date="+today+"&time="+GMTtime;  ^M
"

After this change I get the correct image for map.

Thanks!

**Comment by mykle1** [comment]
I appreciate that you took the initiative to fix the issue you are having but the module runs as expected here on several machines. Thank you for your interest. Peace!
