### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by pepebc** [mykle1/MMM-SunRiseSet#2]
Spanish translation and files for translations directory,
It will be necessary to change the lines in the file MMM-SunRiseSet.js

On directory /translations/ :

en.json:
```
{
"Sunrise is at ": "Sunrise is at ",
"Sunset is at ": "Sunset is at ",
"Solar noon is at ": "Solar noon is at ",
"Length of day is ": "Length of day is ",
"Civil twilight begins at ": "The next new moon is ",
"Civil twilight ends at ": "Civil twilight ends at ",
"Nautical twilight begins at ": "Nautical twilight begins at ",
"Nautical twilight ends at ": "Nautical twilight ends at ",
"Astronomical twilight begins at ": "Astronomical twilight begins at ",
"Astronomical twilight ends at ": "Astronomical twilight ends at "
}
```
es.json:

```
{
"Sunrise is at ": "Sale el Sol a las ",
"Sunset is at ": "Se pone el Sol a las ",
"Solar noon is at ": "Mediodia Solar a las ",
"Length of day is ": "La duración del día es ",
"Civil twilight begins at ": "La Nueva Luna Llena ",
"Civil twilight ends at ": "Crepúsculo civil termina ",
"Nautical twilight begins at ": "Crepúsculo náutico comienza ",
"Nautical twilight ends at ": "Crepúsculo náutico termina ",
"Astronomical twilight begins at ": "Crepúsculo astronómico comienza ",
"Astronomical twilight ends at ": "Crepúsculo astronómico termina "
}
```

**Comment by mykle1** [comment]
This is not really an issue. There's nothing wrong with the module. It's more of a request on your part. It requires me to do more editing than I have time for at the moment. So, if you please, you can open the MMM-SunRiseSet.js file and go to line 103. Starting there you can manually change the English phrases to Spanish. Just move down through the code from there and change each phrase and it will work for you. If I get time in the future I will see what I can do. Thanks for your interest. Peace!
