### ISSUE TITLE
wrong url for getting map info, again

### ISSUE THREAD

**Issue by rosenberg-c** [mykle1/MMM-SunRiseSet#3]
Hello!
The url for the map does not work for me either, as the other issue that is closed said.

I tryed the proposed change, but it did not get it to work.
Perhaps i made the change in the wrong place.

**Comment by mykle1** [comment]
Hi, I didn't propose any change as the module works as expected. This url for the map http://api.usno.navy.mil/imagery/earth.png?date=today works. Try it in your browser. The seed at the end of it in the code is there to refresh the image. I just downloaded the module again and installed it on yet another machine and it fires right up. Sometimes the image can take a few extra seconds to load so please be patient. Perhaps you should try deleting the module folder and install it again. Please contact me in the forum if you have any more difficulty. Thanks
