### ISSUE TITLE
URL for Map not working again

### ISSUE THREAD

**Issue by leekis** [mykle1/MMM-SunRiseSet#6]
Saw the other 2 same issues closed so I checked the links and they don't work. Seems the Navy site is shut down. Any thoughts on a new link that would make the map work?
Thx.
Ki

**Comment by mykle1** [comment]
The USNO api is down for repairs/upgrades. The projected completion is April/2020. That map with the darkness animation is specific to the api. Not much I can do about that. I'm going to wait for the api. Feel free to fork the repo and make your changes and additions if you like. Thanks for your interest in the module
