### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by GoodWillGustin** [mykle1/MMM-SunRiseSet#7]
I just installed the module and the images for 'world and ''map" are not loading. "static" works. Is the source they are being pulled from unavailable? Here is my config and a screenshot of what ends up displaying in MM:

{
	disabled: false,
	module: "MMM-SunRiseSet",
	position: "bottom_center",
		config: {
	lat: "mylat",
	lng: "mylng",
	image: "world", //"world" (animation), "map" (animation), "static" (graph)
	imageOnly: "yes",       // no = all data, yes = only animated world or map
	dayOrNight: "day",   // "night" approaching, "day" approaching (imageOnly: must be "yes", image: must be "world") 
	useHeader: true,      // true if you want a header
	header: "Daylight",      // useHeader must be true
	maxWidth: "515px", //default was 515px
			}
	},

![mmm-sunriseset error](https://user-images.githubusercontent.com/58321783/71187537-41ccfa00-224d-11ea-8e8f-9578447da9be.PNG)

**Comment by mykle1** [comment]
Hey, sorry about that. Yes, the USNO api is down until April.
