### ISSUE TITLE
USNO API

### ISSUE THREAD

**Issue by GoodWillGustin** [mykle1/MMM-SunRiseSet#8]
Hey, I know you mentioned the USNO API is down and was expected to be completed April 2020, but for me the animated maps are not working. Do you know if there is somewhere that has a status update I can follow? I hate to keep bothering you directly. Thanks.

**Comment by mykle1** [comment]
That is because the animated maps come from the usno api which is now reporting the end of the summer as a possible date to become active again. You could go the usno api website. you'll see anouncement there
